//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankCusManagement.Models
{
    using System;
    
    public partial class GetTransactionsByDate_Result1
    {
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> Noofcustomers { get; set; }
        public string TypeOf_Transaction { get; set; }
    }
}
