//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankCusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_customers()
        {
            this.tbl_customer_transactions = new HashSet<tbl_customer_transactions>();
        }
    
        public int Cust_Id { get; set; }
        public int Uid { get; set; }
        [Display(Name = "FirstName")]
        public string Customer_FirstName { get; set; }
        [Display(Name = "LastName")]
        public string Customer_LastName { get; set; }
        [Display(Name = "City")]
        public string Customer_City { get; set; }
        [Display(Name = "Account Type")]
        public string Account_Type { get; set; }
        [Display(Name = "Account Balance"), Range(1, 50000, ErrorMessage = "Amount should be min ₹1 and max ₹50000")]
        public Nullable<double> Account_BalanceAmount { get; set; }
        [Display(Name = "Last Transaction Date")]
        public Nullable<System.DateTime> Last_TransactionDate { get; set; }
        [Display(Name = "Customer Code")]
        public string Customer_Code { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_customer_transactions> tbl_customer_transactions { get; set; }
        public virtual tbl_users tbl_users { get; set; }
    }
}
