//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankCusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_role_menu
    {
        public int Menu_Id { get; set; }
        public string Menu_Name { get; set; }
        public int Role_Id { get; set; }
    
        public virtual tbl_Roles tbl_Roles { get; set; }
    }
}
