//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankCusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_users()
        {
            this.tbl_customers = new HashSet<tbl_customers>();
        }
    
        public int Uid { get; set; }
      
        public string Login_Id { get; set; }
       
        public string Password { get; set; }
        public string User_Name { get; set; }
        public int Role_ID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Last_Login { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_customers> tbl_customers { get; set; }
        public virtual tbl_Roles tbl_Roles { get; set; }
    }
}
